### ISSUE TITLE
dbmonster

### ISSUE THREAD

**Issue by crcn** [mojo-js/paperclip.js#213]
https://github.com/wycats/dbmonster/
https://github.com/ryanflorence/reactconf-2015-HYPE/tree/master/demos/01-dbmon

**Comment by crcn** [comment]
done-zo

**Comment by guilhermeaiolfi** [comment]
WOW! So fast. Why paperclip.js is so under publicized?

That example is one case that a simple tweet could drag a lot o attention to the project since dbmonster has a certain momentum.

**Comment by crcn** [comment]
I think you're correct that it'll take probably one strong message to get PaperclipJS promoted - but I think there's general exhaustion in the community about the number of templating / view libraries. It might be hard to promote Paperclip right now.

That, stability (paperclip is - has been for 2 years), dev experience, and community around a library are also necessary for it to be adopted, so there's a bit of a chicken / egg problem there. 

Currently working on some stuff to hopefully get the word out - definitely open to other ideas though.

**Comment by guilhermeaiolfi** [comment]
Well, I saw that you were working in paperclip's components. Maybe the documentation could be around that since everyone is shifting to that kind of style now. I'm using ractive right now, but I always keep an eye to see what is happening around. I recently switched from ember. So maybe some examples comparing paperclip to two or three mainstream frameworks could give a sense of how paperclip is and what would be the advantages. 

One concern that I have is that this project seems to have just you as a contributor. It's very risk to adopt it since you can drop it anytime. If that's not the case, it could/should be shown somehow.

**Comment by crcn** [comment]
More docs on components would be a good idea I think. There isn't anything on the home page right now that really shows the differences between paperclip & other frameworks - I was thinking of doing a series of blog posts about that kinda stuff. 

And yeah, 1 contributor on this project is certainly a deal breaker for most production apps -  definitely #1 priority to get more adoption.
