### ISSUE TITLE
can i change interpolation syntax?

### ISSUE THREAD

**Issue by devmondo** [mojo-js/paperclip.js#227]
this is like outstanding library, thank you very much for it :)

i am wondering if i can customize some stuff like below,

also what is the technique used to make this binding is it dirty checking, proxy, object.observe and what is the performance?

thanks in advanced. 

note the comment 
```
Two-way binding:
//for example replace {{}} with {} 
//for example replace value="{{ <~>name }}" with two-way="{name}" or better two-way="name"
<input class="form-control" value="{ <~>name }" />

Bind input value to name only:
//for example replace value="{{ ~>name }}" with one-way="{name}" or better one-way="name"
<input class="form-control" value="{{ ~>name }}" />

Bind name to input value only:

<input class="form-control" value="{{ <~name }}" />

Unbound helper - don't watch for any changes:
{{ ~name }}
```

**Comment by crcn** [comment]
Hey - glad you like the library! 

To answer some of your questions:

> //replace {{}} with {} 

Right now there isn't an elegant way to do this. I've been thinking about dropping the double brackets for single brackets - definitely makes the code more readable. 

I've also been thinking about adding additional parsers for the library - or separating the parser altogether so that you could translate other templating engines over to paperclip - might actually do that here in the near future. 

In the meantime, here's a short fix to your problem that should be performant:

```javascript
var src = "{hello}";

// replace single {} with double {}
src = tpl.replace(/\{(.*?)\}/g, "{{$1}}");
var tpl = pc.template(src);
```

Note that there *might* be some edges to the block above - dunno if it'll work for every case as it is.

> //for example replace value="{{ ~>name }}" with one-way="{name}" or better one-way="name"

The only way to do explicit bindings is through the operators: `~` (unbound), `<~>` (two-way), and `~>` (one-way). The reason for this is because it's super flexible. Take for example a component you might have embedded in your app:

```html
<selectMenu items={{items}} selectedItem={{<~>selectedItem}} />
```

the `<~>` ensures that the `selectedItem` attribute is properly sync between the `selectMenu` component, and whatever component is using it. 

> also what is the technique used to make this binding is it dirty checking, proxy, object.observe and what is the performance?

You can easily build out your own custom `accessor`. Here's the docs: http://paperclipjs.com/advanced-api

Here's a dirty-type checker accessor: https://github.com/mojo-js/paperclip.js/blob/master/lib/accessors/pojo.js
Here's a [bindable-object](https://github.com/mojo-js/bindable-object.js) accessor: https://github.com/mojo-js/paperclip-todomvc-example/blob/master/app/js/accessor.js (Note: Use [watchable-object](https://github.com/mojo-js/watchable-object.js) instead)

More stuff to come - thanks for the support!

**Comment by devmondo** [comment]
man, such an awesome reply, thank you very much, i set my mind to use this, it is just beautiful :)
