### ISSUE TITLE
Add method for binding to dom properties (maybe syntax extension)

### ISSUE THREAD

**Issue by matthewrobb** [mojo-js/paperclip.js#246]
Right now if I try to pass an object as an attribute it would likely end up being `prop="[object Object]"` but what I'd like to be able to do is explicitly pass a property/attribute that is not set using setAttribute rather instead it is set using assignment:
```html
<div .data={{ someObject }}></div>
```
although having an explicit syntax extension seems reasonable I do think the better approach would be to have it so any attribute that is not quoted gets treated as a SET operation on the node rather than using setAttribute. I believe this is how HTMLBars works and also Polymer:
```html
<div data={{ someObject }}>A</div>
<div data="{{ someObject }}">B</div>
```
With the above template, A will end up with no data attribute when inspected but will have a data property and B will work exactly as things do already.

**Comment by matthewrobb** [comment]
I wouldn't mind investigating this a bit further if you could tip me in the right direction and what an acceptable end-result should look like for you.

**Comment by crcn** [comment]
Definitely like the approach of having an explicit way of defining whether to set a property or an attribute on a DOM node - just a matter of mulling over the proper syntax for it. Not a huge fan of introducing a new operator, but that approach seems to make the most sense. So going with an approach similar to polymer, we might get something like this:


```html

<!-- input.value = something -->
<input value$={{ something }} />

<!-- input.setAttribute("value", something);
<input value={{ something }} />
```

Another approach using quotes:

```html

<!-- input.value = something -->
<input value={{ something }} />

<!-- input.setAttribute("value", something);
<input value="{{ something }}" />
```

The above approach maybe an appropriate option since quotes denote the value will be cast as a string (attribute values are), whereas the absence of quotes can be any data type. 

Also some ideas about an operator before the attribute name - something that denotes a sort-of `this` statement, or similar:

```html
<input .value="blah" />
<input @value="something" />
<input property.value="something" />
```

Lmk what you think.

**Comment by matthewrobb** [comment]
Personally I prefer using quotes as it feels very natural and also that's the way HTMLBars went. Since 99% of the time people will mark up their elements using quoted values I think it makes a lot of sense because leaving the quotes off (while subtle, sure) looks intentional.

**Comment by crcn** [comment]
Totally agree. Gonna go ahead and implement this then. Thanks for the feedback!

**Comment by crcn** [comment]
This is now implemented in the `3.x` branch: https://github.com/mojo-js/paperclip.js/blob/3.x/lib/compiler-test.js#L65
