### ISSUE TITLE
Repeat blocks/components do not render unless their repeated items change

### ISSUE THREAD

**Issue by AutoSponge** [mojo-js/paperclip.js#276]
https://jsbin.com/zamana/edit?js,console,output

In this scenario, I have something to repeat and inside the repeat block, I use other data from the view to properly render each item. However, updating this data does not cause the `repeat` block to re-render. I've deduced that only changes to the object being repeated will cause a re-render of the `repeat` block/component.

Is there a way to bind the `repeat` block to this additional data?

**Comment by AutoSponge** [comment]
I'm able to force an update with this snippet:

```javascript
    view.bindings.forEach(function (b) {
      if (!b.component) return;
      b.component._children.forEach(function (c) {
        c.bind(c.context);
      });
    });
```

Do I need to construct my own "bound" repeat component that adds this snippet as a watcher?

**Comment by crcn** [comment]
Doesn't look like there's a nested repeat block. Do you have an updated example?

**Comment by AutoSponge** [comment]
This issue doesn't deal with nesting.

**Comment by crcn** [comment]
Got it, thanks for clarifying. This is a bug.

The attributes in the `<repeat />` component never change, and so `Repeat.update()` never gets fired. The solution to this is to `update()` each component whenever `view.set(...)` gets called, just like your approach above. This also lines up nicely with `3.x` stuff since I plan to remove a lot of the state that goes on within paperclip.

I'll patch this up and push to the `2.x` branch here in a bit.

**Comment by crcn** [comment]
Must merged `3.x` into master which has fewer moving parts. This should be fixed now.
