### ISSUE TITLE
ability to pass options to transpiler

### ISSUE THREAD

**Issue by crcn** [mojo-js/paperclip.js#281]
```javascript
pc.transpile("{{source}}", { metal: true });
```

For additional optimizations.

**Comment by AutoSponge** [comment]
I would like to see more build support through the cli or an api (I may be able to take a look at this). My current issue is I'm using browserSync for the dev server and when I touch an .html file, I have to recompile templates. This is an iterative process in the shell which causes several flashes of browserSync before the templates are compiled to js. If I could batch them or create a `gulp` handler, it would be smoother.

If you want, I can share more of my workflow since we're using `jspm` and `babel` to es6ify all the things. I think including other transpilers as middleware would allow for many workflow variations.

**Comment by crcn** [comment]
Yeah totally - any context around what you're doing with paperclip would help!
